services:
  heremio:
    build: .
    container_name: heremio
    restart: unless-stopped
    ports:
      - "${PORT:-9000}:${PORT:-9000}"
    env_file:
      - .env
    environment:
      CACHE_FILE: /app/data/cache.json
    volumes:
      - stashdb_cache:/app/data

volumes:
  stashdb_cache:
